#!/bin/bash

domain="$1"
subdomain="$2"

# Define the subdomains and their IP addresses
subdomains=("www" "lb-01" "web-01" "web-02")
ip_addresses=("54.210.47.110" "54.210.47.110" "34.198.248.145" "54.89.38.100")

# Check if both domain and subdomain are provided
if [[ -z "$domain" ]]; then
    echo "Missing domain argument."
    exit 1
fi

# Iterate through subdomains and display information
for ((i=0; i<${#subdomains[@]}; i++)); do
    if [[ -z "$subdomain" ]] || [[ "$subdomain" == "${subdomains[i]}" ]]; then
        record_type=$(dig ${subdomains[i]}.$domain +short -t A | awk '{print $1}')
        destination=$(dig ${subdomains[i]}.$domain +short -t A | awk '{print $1}')
        echo "The subdomain ${subdomains[i]} is a $record_type record and points to $destination"
    fi
done
